INSERT INTO administrativa.tipo_nomina(nombre,descripcion,activo) VALUES ('FP','Funcionarios administrativos',TRUE);
INSERT INTO administrativa.tipo_nomina(nombre,descripcion,activo) VALUES ('DP','Docentes de planta',TRUE);
INSERT INTO administrativa.tipo_nomina(nombre,descripcion,activo) VALUES ('PE','Pensionados',TRUE);
INSERT INTO administrativa.tipo_nomina(nombre,descripcion,activo) VALUES ('HCH','Hora cátedra honorarios',TRUE);
INSERT INTO administrativa.tipo_nomina(nombre,descripcion,activo) VALUES ('HCS','Hora cátedra salarios',TRUE);
INSERT INTO administrativa.tipo_nomina(nombre,descripcion,activo) VALUES ('CT','Contratistas',TRUE);

INSERT INTO administrativa.nomina(descripcion, tipo_nomina, activo) VALUES ('Funcionarios administrativos - Planta ', 4 , TRUE);

INSERT INTO administrativa.estado_preliquidacion(nombre, descripcion, activo) VALUES ('Cerrada', 'No se permiten más cambios en la preliquidación pues ya ha sido liquidada', TRUE);
INSERT INTO administrativa.estado_preliquidacion(nombre, descripcion, activo) VALUES ('Abierta', 'La preliquidación puede volver a calcularse', TRUE);
INSERT INTO administrativa.estado_preliquidacion(nombre, descripcion, activo) VALUES ('SolicitudNecesidad', 'Se ha solicitado una necesidad para esta preliquidación', TRUE);

INSERT INTO administrativa.tipo_concepto_nomina(nombre, descripcion, activo) VALUES ('fijo', 'Concepto cuyo valor no cambia', TRUE);
INSERT INTO administrativa.tipo_concepto_nomina(nombre, descripcion, activo) VALUES ('porcentual', 'Concepto que cambia según el porcentaje indicado', TRUE);
INSERT INTO administrativa.tipo_concepto_nomina(nombre, descripcion, activo) VALUES ('seguridad_social', 'Concepto de seguridad social', TRUE);

INSERT INTO administrativa.naturaleza_concepto_nomina(nombre, descripcion, activo) VALUES ('devengo', 'Concepto que suma al pago del empleado', TRUE);
INSERT INTO administrativa.naturaleza_concepto_nomina(nombre, descripcion, activo) VALUES ('descuento', 'Concepto que se resta al pago del empleado', TRUE);
INSERT INTO administrativa.naturaleza_concepto_nomina(nombre, descripcion, activo) VALUES ('seguridad_social', 'Concepto de seguridad social', TRUE);

INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1261,'primaNavidad', 'Prima de Navidad', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1263,'interesCesantias', 'Intereses de Cesantias', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1264,'bancoPichincha', 'Banco Pichincha', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1265,'adultoMayor', 'Adulto Mayor', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1266,'pagoBruto', 'Pago Bruto', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1267,'rete383', 'Retencion en la fuente (Articulo 383)', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1268,'reteIca', 'Retencion de Industria y Comercio (ICA)', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1269,'estampillaUD', 'Estampilla UD', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1270,'proCultura', 'Pro-Cultura', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1271,'rete384', 'Retencion en la fuente (Articulo 384)', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1262,'cesantias', 'Censantías', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1,'nombreRegla1', 'Carga horaria', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1172,'nombreRegla1172', 'Ajuste Fav. Plan Cafe', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1173,'nombreRegla1173', 'Ajuste Fav. Upc Cafe', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1174,'primaAnt', 'Prima por antigüedad', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1175,'primaSecr', 'Prima secretarial', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1176,'nombreRegla1176', 'Ajuste Prima Secretarial', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1177,'nombreRegla1177', 'Ajuste Prima Por Antiguedad', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1178,'nombreRegla1178', 'Ajuste', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1179,'nombreRegla1179', 'Doceava Bonificacion Por Serv', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1180,'nombreRegla1180', 'Bonif. Esp. Recreación', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1181,'nombreRegla1181', 'Ajuste Bonif. Recreación', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1182,'nombreRegla1182', 'Ajuste Decreto 4153-04', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1183,'nombreRegla1183', 'Mesadas Atrasadas', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1184,'nombreRegla1184', 'Coordinación Académica', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1185,'nombreRegla1185', 'Ajuste Coord. Académica', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1187,'nombreRegla1187', 'Ajuste Fav. Upc Sanitas', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (194,'nombreRegla194', 'Devolucion Sanción', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1188,'nombreRegla1188', 'Devolución Medisanitas', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1199,'nombreRegla1199', 'Indexación', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1190,'nombreRegla1190', 'Dev. Increm. Cot. Salud', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1191,'nombreRegla1191', 'Dev. Fondo Solidaridad', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (115,'nombreRegla115', 'Prima alimentación', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (116,'nombreRegla116', 'Quinquenio', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (117,'nombreRegla117', 'Vacaciones en dinero', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (120,'nombreRegla120', 'Ajuste U.D. Préstamo', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (121,'nombreRegla121', 'Intereses cesantías', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (123,'nombreRegla123', 'Cesantías', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (124,'nombreRegla124', 'Ajustes a favor', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (125,'nombreRegla125', 'Devolución regimen salud', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (126,'nombreRegla126', 'Auxilio maternidad', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (127,'nombreRegla127', 'Fracción Quinquenio', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (130,'nombreRegla130', 'Reliq.Sueld.Vacación', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (132,'nombreRegla132', 'Reliq.Prima Sevicios', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (133,'nombreRegla133', 'Prima vacaciones', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (136,'nombreRegla136', 'Reliquida Quinquenio', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (150,'nombreRegla150', 'Prestaciones sociales', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (151,'nombreRegla151', 'Ajuste Sueldo', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (153,'nombreRegla153', 'Ajuste Sobresueldo', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (154,'nombreRegla154', 'Ajuste Pensión', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (155,'nombreRegla155', 'Ajuste Subsidio Familiar', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (156,'nombreRegla156', 'Ajuste subsidio transporte', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (157,'nombreRegla157', 'Ajus. Recar.Nocturno', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (159,'nombreRegla159', 'Ajuste Honorarios', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (160,'nombreRegla160', 'Ajuste Sueldo vacaciones', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (161,'nombreRegla161', 'Ajuste Prima Técnica', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (162,'nombreRegla162', 'Ajuste Prima Servicios', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (163,'nombreRegla163', 'Ajuste Prima Vacaciones', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (164,'nombreRegla164', 'Ajuste Prima Navidad', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (165,'nombreRegla165', 'Ajuste Prima Alimentación', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (166,'nombreRegla166', 'Ajuste Quinquenio', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (169,'nombreRegla169', 'Intereses Cesantías', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (170,'nombreRegla170', 'Quinquenio.Proporcio', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (171,'nombreRegla171', 'Ajuste Inter.Cesant.', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (172,'nombreRegla172', 'Ajuste Cesant Parcial', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (173,'nombreRegla173', 'Ajuste Cesantias', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (174,'nombreRegla174', 'Ajuste Sueldo Retroactivo', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (177,'nombreRegla177', 'Devolución Sintraud', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (178,'nombreRegla178', 'Ajuste Horas Extras', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (179,'nombreRegla179', 'Prim.Semes.Proporcio', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (180,'nombreRegla180', 'Bonificacion Extra_C', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (181,'nombreRegla181', 'Devolución Retención', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (182,'nombreRegla182', 'Prim.Vac.Proporciona', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (183,'nombreRegla183', 'P.Adicional Aliment.', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (184,'nombreRegla184', 'Suel.Vac.Proporcion', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (186,'nombreRegla186', 'Pago Curso Vacaciones', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (187,'nombreRegla187', 'Prestaciones Sociales', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (188,'nombreRegla188', 'Ajuste Contrato', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (190,'nombreRegla190', 'Devol.Regimen Pensiones', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (113,'priVac', 'Prima de vacaciones', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (114,'nombreRegla114', 'Prima de navidad', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1100,'nombreRegla1100', 'Pago Docentes V. Especial', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1101,'nombreRegla1101', 'Ajuste F. Pag. Docente. V.Esp', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (140,'nombreRegla140', 'Incremento Cot.Salud', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (189,'nombreRegla189', 'Auxilio Matrimonio', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1104,'nombreRegla1104', 'Ajuste Fav.Incapacidad', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1107,'nombreRegla1107', 'Ajuste Decreto 2880-01', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (135,'nombreRegla135', 'Plan Complemen.Salud', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (137,'nombreRegla137', 'Devol.Circulo Lectors', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1109,'nombreRegla1109', 'Saludcoop', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2282,'nombreRegla2282', 'Martha Molina  Sub-Libros', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1272,'primaVacaciones', 'Prima de Vacaciones', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1273,'vacaciones', 'Vacaciones', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (144,'nombreRegla144', 'Incremento Cot. Salud', 2, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2188,'nombreRegla2188', 'Ajubilud Emergencia Juridica', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2172,'nombreRegla2172', 'A.C. Estimulo Investigadores', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2174,'nombreRegla2174', 'Compensar Salud', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2175,'nombreRegla2175', 'Medisanitas S.A.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2176,'nombreRegla2176', 'Colsanitas S.A.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2177,'nombreRegla2177', 'Opticas Gammaluz', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2181,'nombreRegla2181', 'A.C. Pri. Tecnica Pr. Vac 2003', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2183,'nombreRegla2183', 'Banco Popular - Credito', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2184,'nombreRegla2184', 'Aspu - Ud Descuento Especial', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2185,'nombreRegla2185', 'Colmena', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2186,'nombreRegla2186', 'Emermedica S.A.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2187,'nombreRegla2187', 'A.C. Retencion-Fuente', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2189,'nombreRegla2189', 'Casa Nacional Del Conductor', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2190,'nombreRegla2190', 'Banco Granahorrar-Credito', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2192,'nombreRegla2192', 'Diana Carolina Mendez Morato', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2193,'nombreRegla2193', 'Crediservicios S.A.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2194,'nombreRegla2194', 'Grupo Cinco Estrellas', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2195,'nombreRegla2195', 'Upc Sanitas', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2196,'nombreRegla2196', 'Pen.Voluntaria Santander', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (141,'nombreRegla141', 'Devolución Reg.Salud', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (138,'nombreRegla138', 'Devolución A.D.U.D.', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1103,'nombreRegla1103', 'Caprecom', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (139,'nombreRegla139', 'Ajuste Bonif.Servicios', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (191,'nombreRegla191', 'Estimulo Investigadores', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2209,'nombreRegla2209', 'Seguros De Vida Colpatria S.A', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (131,'nombreRegla131', 'Bonif. Jurados Concursos Doc.', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1200,'nombreRegla1200', 'Ajuste Decreto 615-07', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1192,'nombreRegla1192', 'Ajuste Prima Vacaciones Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1193,'nombreRegla1193', 'Ajuste Sueldo Vacaciones Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1194,'nombreRegla1194', 'Ajuste Prima Navidad Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1195,'nombreRegla1195', 'Ajuste Bonif. X Serv. Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1196,'nombreRegla1196', 'Ajuste Prima Servicios Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1197,'nombreRegla1197', 'Ajuste Vacaciones Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1201,'nombreRegla1201', 'Ajuste Prima Tecnica Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1202,'nombreRegla1202', 'Ajuste Prima Antig. Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1203,'nombreRegla1203', 'Ajuste Decreto 627-08', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1112,'nombreRegla1112', 'Mesada Adicional Junio', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1204,'nombreRegla1204', 'Dev. 0.5% Cotsalud L 1250/08', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1206,'nombreRegla1206', 'Ajuste Gtos. Repres. Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1215,'nombreRegla1215', 'Bono Extr. Prod. Soc. R168.09', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1209,'nombreRegla1209', 'Ajuste Horas Extras Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1210,'nombreRegla1210', 'Ajuste Prima Secretarial Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1212,'nombreRegla1212', 'Ajuste Bonif. Recreacion Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1214,'nombreRegla1214', 'Aju. Asig. Adic Dec. Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1216,'nombreRegla1216', 'Aju.Suel.Bás. X Exc.Acad.05.08', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1217,'nombreRegla1217', 'Aju.Prim.Sem  X Exc.Acad.05.08', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1218,'nombreRegla1218', 'Aju.Prim.Nav.X Exc.Acad.05.08', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1219,'nombreRegla1219', 'Aju.Suel.Vac. X Exc.Acad.05.08', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1221,'nombreRegla1221', 'Aju.Bo.X Serv X Exc.Acad.05.08', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1222,'nombreRegla1222', 'Ajuste Prima Servic  Asig Adic', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1223,'nombreRegla1223', 'Ajuste Mesada Adicional Junio', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1224,'nombreRegla1224', 'Sueldo Básico V.', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1225,'nombreRegla1225', 'Prima Técnica V', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1226,'nombreRegla1226', 'Prima Antig. V', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1227,'nombreRegla1227', 'Gastos Rep. V', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1228,'nombreRegla1228', 'Prima Alimen. V', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1229,'nombreRegla1229', 'Sub Transporte V', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1230,'nombreRegla1230', 'Asig. Adic. Decreto. V', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1231,'nombreRegla1231', 'Doce. Prima Servicios V', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1232,'nombreRegla1232', 'Doce. Bon Servicios V', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1233,'nombreRegla1233', 'Doce. Quinquenio V', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1235,'nombreRegla1235', 'Aju Mesada Por Retro 2.4% 2010', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1236,'nombreRegla1236', 'Aju Mes Adic Dic Por Retr 2.4%', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1237,'nombreRegla1237', 'Ajuste Fav. Plan Famisanar', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1238,'nombreRegla1238', 'Ajuste Sueld.Vac.Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1239,'nombreRegla1239', 'Ajuste P.Tecni. Vac.Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1240,'nombreRegla1240', 'Ajuste P.Anti.Vac.Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1241,'nombreRegla1241', 'Ajuste Doce P. Servi.Vac.Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1242,'nombreRegla1242', 'Ajuste Doce Bonif.Vac.Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1243,'nombreRegla1243', 'Ajuste Vac.Diner.Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1244,'nombreRegla1244', 'Ajuste Bonif.X Rec.Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1246,'nombreRegla1246', 'Aju Mesada Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1247,'nombreRegla1247', 'Ajuste Interes Salud,Pen, F.S', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1248,'nombreRegla1248', 'Ajuste Asig.Adic.Decreto V.', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1249,'nombreRegla1249', 'Ajuste Doce. Boni.Servicios V.', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1250,'nombreRegla1250', 'Ajuste Doce. Prima Servicios V', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1251,'nombreRegla1251', 'Ajuste Gastos Rep.V', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1252,'nombreRegla1252', 'Ajuste Prima Antg. V', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1253,'nombreRegla1253', 'Ajuste Prima Tecnica V.', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1254,'nombreRegla1254', 'Ajuste Sueldo Basico V', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1255,'nombreRegla1255', 'Ajuste Mesada Adicional Dic.', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1256,'nombreRegla1256', 'Ajuste Incremento Cot.Salud', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1258,'nombreRegla1258', 'Ajuste Prima Adicional Diciemb', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1259,'nombreRegla1259', ' 1.2 Convencional Junio', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1260,'nombreRegla1260', 'Intereses Por Mora Segun Fallo', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (231,'nombreRegla231', 'Feud Aportes', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (237,'nombreRegla237', 'U.D. Ley 33', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (239,'salud', 'Régimen salud', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (265,'nombreRegla265', 'Aspu-Ud', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2126,'nombreRegla2126', 'Ajubilud', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (211,'nombreRegla211', 'A. D. E. - U.D.', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2206,'nombreRegla2206', 'Coop. Prof. Univ. Nal.', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2173,'nombreRegla2173', 'Pen. Voluntaria Porvenir', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2197,'nombreRegla2197', 'Suramericana De Seguros', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2199,'nombreRegla2199', 'Cooproser Ltda', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2200,'nombreRegla2200', 'Agricola De Seguros S.A.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2201,'nombreRegla2201', 'A.C. Pago Curso Vacac.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2202,'nombreRegla2202', 'Suma Emergencias S.A.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2203,'nombreRegla2203', 'Agricola De Seguros S.A.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2204,'nombreRegla2204', 'Luz Marina Varela', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (210,'nombreRegla210', 'Retencion - Fuente', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (214,'nombreRegla214', 'U.D. Préstamo', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (216,'nombreRegla216', 'Banco Agrario', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (217,'nombreRegla217', 'Canapro Libranza', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (218,'nombreRegla218', 'A.C. Prima Técnica', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (219,'nombreRegla219', 'Matricula Postgrado', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (220,'nombreRegla220', 'A.C. Prima Semestral', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (221,'nombreRegla221', 'Feud Fomento', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (222,'nombreRegla222', 'A.C.Prima Vacaciones', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (24,'nombreRegla24', 'FeUD Prest.Extraord.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (25,'nombreRegla25', 'A.C.Gtos Representa.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (26,'nombreRegla26', 'Canapro Acciones', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (27,'nombreRegla27', 'Coopcedral Ltda', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2136,'nombreRegla2136', 'UDnet Servicios', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2132,'nombreRegla2132', 'Compensar Credito', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2133,'nombreRegla2133', 'Compensar Prepagada', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2150,'nombreRegla2150', 'Coopacon Libranza', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (292,'nombreRegla292', 'Alejandrina Morales', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (293,'nombreRegla293', 'Soc.Col.Matematicas', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (294,'nombreRegla294', 'Feud Consumo', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (295,'nombreRegla295', 'Maria E. Martinez A.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (296,'nombreRegla296', 'Aura Ospino', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (297,'nombreRegla297', 'Rosa Elena Suarez A.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (298,'nombreRegla298', 'Coahorro Ltda', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2100,'nombreRegla2100', 'Ajuste C. Pag. Docente. V.Esp', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (223,'nombreRegla223', 'A.C.Int.Cesantias', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (224,'nombreRegla224', 'Codecontra Acciones', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (225,'nombreRegla225', 'La Previsora S.A.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (226,'nombreRegla226', 'AsopenUD Afiliación', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (227,'nombreRegla227', 'Auxilio Mutuario', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (228,'nombreRegla228', 'A.C.Prima Navidad', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (229,'nombreRegla229', 'Prosocial', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (232,'nombreRegla232', 'A.C.Sueldo Vacacion.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (234,'nombreRegla234', 'Carmen Flor Garzon', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (235,'nombreRegla235', 'Club Empleados Ofic.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (236,'nombreRegla236', 'Rosalba Nope Diaz', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (238,'nombreRegla238', 'A.C. Horas Extras', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (240,'nombreRegla240', 'A.C.Prima Alimentac.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (241,'nombreRegla241', 'Asopenud Prestamo', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (242,'nombreRegla242', 'A.C.Prima Antiguedad', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (243,'nombreRegla243', 'Feud Credirapido', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (245,'nombreRegla245', 'A.C.Subsidio Famili.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (246,'nombreRegla246', 'Creditodos', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (247,'nombreRegla247', 'Feud Seguro Vehiculo', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (248,'nombreRegla248', 'Actividad Cultural', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (249,'nombreRegla249', 'A.C. Pension', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (250,'nombreRegla250', 'Codecontra Aux Mutua', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (251,'nombreRegla251', 'Cesantias Pagadas', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (252,'nombreRegla252', 'Aspu-Ud', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (257,'nombreRegla257', 'Cooproccol Ltda', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (258,'nombreRegla258', 'Sintraud Solidaridad', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (259,'nombreRegla259', 'Canapro Dcto. Especial', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (260,'nombreRegla260', 'Dcto Mes Codecontra', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (261,'nombreRegla261', 'Dacreditos S.C.Ltda', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (262,'nombreRegla262', 'Codema Ltda', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (263,'nombreRegla263', 'Feud Centro Vacacion', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (264,'nombreRegla264', 'Samuel Roberto Diaz Olaya', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2116,'nombreRegla2116', 'Martha Cecilia Sandoval M.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2118,'nombreRegla2118', 'Coopacon Ltda Ahorros', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2135,'nombreRegla2135', 'Icetex', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2117,'nombreRegla2117', 'CiiUD', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2119,'nombreRegla2119', 'A.C.Bonific.Libros', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2120,'nombreRegla2120', 'Sintraud Sancion', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2121,'nombreRegla2121', 'Aspu Bono Profesional', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2122,'nombreRegla2122', 'Aig Vida', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2123,'nombreRegla2123', 'Seguros Bolivar', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2127,'nombreRegla2127', 'Codema Aport.Extra', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2128,'nombreRegla2128', 'Aporte Eje Cafetero', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2129,'nombreRegla2129', 'A.C. Auxilio Maternidad', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2130,'nombreRegla2130', 'Ruth Constanza Rincon Mendez', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2131,'nombreRegla2131', 'Luz Marina Florez Perez', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (289,'nombreRegla289', 'Mary Becerra De Forero', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2153,'nombreRegla2153', 'A.C. Fondo Solidaridad Pension', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2154,'nombreRegla2154', 'A.C. S.General Pension', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2155,'nombreRegla2155', 'A.C. Regimen Salud', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2138,'nombreRegla2138', 'Colsubsidio', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2232,'nombreRegla2232', 'Asepad-Ud', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2237,'nombreRegla2237', 'Fond. Pens. Volunt. Proteccion', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2247,'nombreRegla2247', 'Caja De Compensacion Compensar', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (256,'nombreRegla256', 'Codecontra Dcto Esp.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2157,'nombreRegla2157', 'Hugo Alexander Castillo', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2158,'nombreRegla2158', 'Upc Cruz Blanca', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2161,'nombreRegla2161', 'Agripina Medina Gonzalez', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2162,'nombreRegla2162', 'A.C.Consumo Celular', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2163,'nombreRegla2163', 'Inst.Lenguas Ud-Ilud', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2164,'nombreRegla2164', 'Luisa Aldana Briceno', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2166,'nombreRegla2166', 'Retención Icetex', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2167,'nombreRegla2167', 'Class Inversion', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2168,'nombreRegla2168', 'A.C. Plan Cafe', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2169,'nombreRegla2169', 'A.C. Upc Cafe', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2170,'nombreRegla2170', 'Cafe Pergamino', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2101,'nombreRegla2101', 'C.M. Licarseev Ltda', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2102,'nombreRegla2102', 'Fondo Pensión Colpatria', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2104,'nombreRegla2104', 'A.C. Bonific Por Servicios', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2105,'nombreRegla2105', 'Upc Saludcoop', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2107,'nombreRegla2107', 'Codema Libranza', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2108,'nombreRegla2108', 'FeUD Préstamo Pensión', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2111,'nombreRegla2111', 'Asopenud Des.Especial', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2112,'nombreRegla2112', 'Fondo Pensiones Davivir', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2113,'nombreRegla2113', 'Tesorería De Bogotá', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2114,'nombreRegla2114', 'Prieto Asociados Ltda', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2103,'nombreRegla2103', 'Caprecom', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2109,'nombreRegla2109', 'Saludcoop', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2106,'nombreRegla2106', 'Plan Cafe', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2137,'nombreRegla2137', 'UPC Cafe', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2141,'nombreRegla2141', 'Retroactivo Salud', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2142,'nombreRegla2142', 'Humberto Camargo Osorio', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2143,'nombreRegla2143', 'Increditos', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2148,'nombreRegla2148', 'Ajubilud Prestamo', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2144,'nombreRegla2144', 'Sancion Ingresos U.D.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2145,'nombreRegla2145', 'Coopefuac Ltda', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2147,'nombreRegla2147', 'Maria Delia Rincon', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2146,'nombreRegla2146', 'Upc Compensar', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (266,'nombreRegla266', 'U.D. Vivienda Adm.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (267,'nombreRegla267', 'Flor Estrella Guevara R.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (268,'nombreRegla268', 'Cooprogreso', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (270,'nombreRegla270', 'Ana Beatriz Navarret', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (271,'nombreRegla271', 'FeUD educación', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (272,'nombreRegla272', 'Horizonte Educativo Ltda', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (273,'nombreRegla273', 'A C I F', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (276,'nombreRegla276', 'Feud Sorteo', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (277,'nombreRegla277', 'U.D. Vivienda Doc.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (279,'nombreRegla279', 'Davivienda Afc', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (280,'nombreRegla280', 'U.D. Préstamo Docent', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (281,'nombreRegla281', 'U.D Prestamo Academia', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (282,'nombreRegla282', 'Coop-Magistra Ltda', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (283,'nombreRegla283', 'Feud Aportes Volunt.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (284,'nombreRegla284', 'Feud Utiles', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (285,'nombreRegla285', 'A.Contra Sueldo', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (286,'nombreRegla286', 'Feud Prest.Especial', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (287,'nombreRegla287', 'Cocentralcol Ltda', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2139,'nombreRegla2139', 'A.C. Decreto Docente', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2210,'nombreRegla2210', 'Maria M. Briceño-Alimentos', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2211,'nombreRegla2211', 'Maria M. Briceño-Ejecutivo', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2212,'nombreRegla2212', 'Banco Occidente Libranza', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2213,'nombreRegla2213', 'A. C. Upc', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2214,'nombreRegla2214', 'Pedro Deaza', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2215,'nombreRegla2215', 'Coopebis', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2216,'nombreRegla2216', 'Melba Rocio Poveda- Sub. Fami', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2217,'nombreRegla2217', 'Inversora Pichincha', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2219,'nombreRegla2219', 'Andrea Del Pilar Mendez Escoba', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2221,'nombreRegla2221', 'Clinica Galvez', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2222,'nombreRegla2222', 'Jose Alfredo Arroyo Paternina', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2223,'nombreRegla2223', 'A.C. Prima Secretarial', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2224,'nombreRegla2224', 'Maria Gladys Hernandez P.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2225,'nombreRegla2225', 'Seguros Del Estado S.A.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2226,'nombreRegla2226', 'Inverfinanciera S.A.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2228,'nombreRegla2228', 'Asopenud-Colmedica Med.Prepag.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2230,'nombreRegla2230', 'Cootradecun', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2231,'nombreRegla2231', 'Coominobras', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2233,'nombreRegla2233', 'Maria Castillo', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2234,'nombreRegla2234', 'Telefonica Moviles Colombia', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2235,'nombreRegla2235', 'Alba Luz Guacaneme (Desc Volun', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2236,'nombreRegla2236', 'Fond. Pens. Volunt. Proteccion', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2238,'nombreRegla2238', 'Compensar Proteccion Integral', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2239,'nombreRegla2239', 'Dev. 0.005% Cotsalud L 1250/08', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2240,'nombreRegla2240', 'Retroactivo Fondo Solidaridad', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2241,'nombreRegla2241', 'Retroactivo Pensión', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2244,'nombreRegla2244', 'Macrofinanciera', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2245,'nombreRegla2245', 'Upc Famisanar', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2246,'nombreRegla2246', 'A.C. Dev. 0.5% Cotsalud L 1250', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2248,'nombreRegla2248', 'A.C. Vacaciones En Dinero', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2149,'nombreRegla2149', 'Crediservicios S.A.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (13,'nombreRegla13', 'Sobresueldo', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (254,'nombreRegla254', 'SintraUD Afiliación', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2319,'nombreRegla2319', 'Union Sindical Col. De Trabajo', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (11,'salarioBase', 'Sueldo básico', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2274,'nombreRegla2274', 'Asotop.Ud.', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2296,'nombreRegla2296', 'Admin Colect Salud Med Plus', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2297,'nombreRegla2297', 'Afliliacion Adm Ajubilud', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (23,'nombreRegla23', 'AsopenUD', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2182,'nombreRegla2182', 'Ana Maria Galindo Gutierrez', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2205,'nombreRegla2205', 'Coop. De Prof. De La Univ. Nal', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (12,'gastosRep', 'Gastos de representación', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (21,'nombreRegla21', 'Comfenalco', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (16,'nombreRegla16', 'Subsidio transporte', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (17,'nombreRegla17', 'Recargos  nocturnos', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (18,'nombreRegla18', 'Dominicales y festivos', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (233,'nombreRegla233', 'A.C.Subsidio Transp.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (255,'nombreRegla255', 'Feud Autofinanciera', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2124,'nombreRegla2124', 'Martha Lucia Molina R.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2165,'nombreRegla2165', 'Ajubilud Afiliacion', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2115,'nombreRegla2115', 'Luz Marcela Lozano Calder', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (274,'nombreRegla274', 'Feud Educacion Confenalco', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2179,'nombreRegla2179', 'Afc-Bancolombia', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2207,'nombreRegla2207', 'Rigoberto Quintero', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2208,'nombreRegla2208', 'Mireya Velasco', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2242,'nombreRegla2242', 'A.C. Puntos Por Bonificación', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2249,'nombreRegla2249', 'Diana Shirley Mayorga', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2250,'nombreRegla2250', 'A.C. Pension Por Retro 2.4%', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2251,'nombreRegla2251', 'Coomuldesarrollo', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2253,'nombreRegla2253', 'Asopenud Auxilio Funerario', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2252,'nombreRegla2252', 'Asopenud Actividad Cultural', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2254,'nombreRegla2254', 'Asopenud Fondo De Salud', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2255,'nombreRegla2255', 'FeUD Educacion Superior', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2256,'nombreRegla2256', 'FeUD Arreglos Locativos', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2257,'nombreRegla2257', 'FeUD Seguro Incendio', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2258,'nombreRegla2258', 'FeUD Credimpuestos', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2260,'nombreRegla2260', 'Feud Credisalud', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2261,'nombreRegla2261', 'Feud Compra De Vivienda', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2262,'nombreRegla2262', 'A.C.S.General Salud Retro', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2263,'nombreRegla2263', 'Res.Fiscal 50100-0064/06', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2264,'nombreRegla2264', 'Afiliacion Siprud', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2265,'nombreRegla2265', 'SiprUD', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2266,'nombreRegla2266', 'Bbva Libranza', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2267,'nombreRegla2267', 'Davivienda Libranza', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2269,'nombreRegla2269', 'A.C. Regimen Salud', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2270,'nombreRegla2270', 'A.C. Regimen Pension', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2271,'nombreRegla2271', 'A.C. Interes Salud,Pens,F.S', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2272,'nombreRegla2272', 'Maria M. Briceño-Sub. Familiar', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2273,'nombreRegla2273', 'Maria M. Briceño- Sub. Libros', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2275,'nombreRegla2275', 'Lilian Mateus Bacca', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2276,'nombreRegla2276', 'A.C. Sub Familiar Pensionados', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2277,'nombreRegla2277', 'A.C. Sub. Libros Pensionados', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2278,'nombreRegla2278', ' Flor E. Guevara (Sub-Libros)', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2279,'nombreRegla2279', 'A.C Puntos Salariales', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2281,'nombreRegla2281', 'A.C. Bonif. Recreacion', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2283,'nombreRegla2283', 'Ajubilud Telefonia', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2284,'nombreRegla2284', 'Ajubilud Solidaridad', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2285,'nombreRegla2285', 'Ajubilud Exequial', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2286,'nombreRegla2286', 'Libia Denise Cangrejo Algure', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2287,'nombreRegla2287', 'Afc Colpatria', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2288,'nombreRegla2288', 'Citi Libranza', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2289,'nombreRegla2289', 'Cooexpocredit  Libranza', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2291,'nombreRegla2291', 'Luz Marina Varela- Subs.Libros', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2292,'nombreRegla2292', 'Claudia Sofia Molano Perilla', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2293,'nombreRegla2293', 'Retroactivo Fondo Solidaridad', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2294,'nombreRegla2294', 'Bayport Fimsa S.A.S Libranza', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2295,'nombreRegla2295', 'A.C. Reintegro Mesad Adicjunio', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2298,'nombreRegla2298', 'Unad-Universidad Abierta Y A D', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2299,'nombreRegla2299', 'Cruz Helena Munera Gaviria', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2300,'nombreRegla2300', 'Helm Bank Libranza', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2301,'nombreRegla2301', 'Coopetrol', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2302,'nombreRegla2302', 'Plata Ya', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2303,'nombreRegla2303', 'FeUD Unificacion', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2306,'nombreRegla2306', 'FeUD Crediprima', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2307,'nombreRegla2307', 'Afc-Fondo Nal Ahorro', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2308,'nombreRegla2308', 'Afc -Fondo Nal Ahorro', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2310,'nombreRegla2310', 'Excelcredit Sas', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2309,'nombreRegla2309', 'Cooperativa "Somec"', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2311,'nombreRegla2311', 'Sancion Disciplinaria', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2312,'nombreRegla2312', 'Toronto Global Service S.A.S', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2314,'nombreRegla2314', 'Laura Sofia Enciso- Sub. Libro', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2315,'nombreRegla2315', 'Gloria Giraldo', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2316,'nombreRegla2316', 'A.C.Pension Hallazgos Contral', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2317,'nombreRegla2317', 'Upc Aliansalud Eps', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2318,'nombreRegla2318', 'Aporte  Solidaridad Ecuador', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2320,'nombreRegla2320', 'Angela E Giraldo Aristizabal', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2321,'nombreRegla2321', 'Johana Paola Londoño Cardenas', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (19,'nombreRegla19', 'Sueldo básico', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (176,'horasExtras', 'Horas Extras', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (290,'fondoSolidaridad', 'Fondo Solidaridad Pensión', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (291,'pension', 'Sistema general de pensión', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2159,'nombreRegla2159', 'Cafam', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (269,'nombreRegla269', 'Feud Ahorro Permanente', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (275,'nombreRegla275', 'Regimen Salud', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2218,'nombreRegla2218', 'Caja De Compensación', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (111,'priTec', 'Prima técnica', 2, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (29,'nombreRegla29', 'SintraUD', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (22,'nombreRegla22', 'Codecontra Ltda.', 2, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (118,'nombreRegla118', 'Prima de antigüedad', 2, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2178,'nombreRegla2178', 'Pen. Voluntaria Dafuturo', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2180,'nombreRegla2180', 'A.C. Pri. Tecnica S. Vac 2003', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2191,'nombreRegla2191', 'A.C. Coordinacion Academica', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1186,'nombreRegla1186', 'Puntos Bonificación', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2198,'nombreRegla2198', 'A.C. Subsidio Familiar', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1189,'nombreRegla1189', 'Devolución Cruz Blanca', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (212,'nombreRegla212', 'FeUD Préstamo', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (213,'nombreRegla213', 'Coopzamora Ltda.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (215,'nombreRegla215', 'FeUD Vivienda', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (119,'subLibros', 'Subsidio libros', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (122,'nombreRegla122', 'Cesantías parciales', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (128,'nombreRegla128', 'Devolución seminario taller', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (134,'nombreRegla134', 'Reliq.Prima.Navidad', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (152,'nombreRegla152', 'Ajuste Gastos Representación', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (158,'nombreRegla158', 'Ajuste Festivos', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (167,'nombreRegla167', 'Ajuste Vacaciones en dinero', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (168,'nombreRegla168', 'Ajuste Prima Antig.', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (175,'nombreRegla175', 'Ajus.U.D Prestaciones', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (185,'nombreRegla185', 'Prim.Nav.Proporcional', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (28,'nombreRegla28', 'A.C. Sobresueldo', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (14,'pensionadoPension', 'Pensión', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (15,'subsidioFa', 'Subsidio familiar', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (110,'nombreRegla110', 'Sueldo vacaciones', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (112,'priServ', 'Prima de servicios', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2134,'nombreRegla2134', 'Claudia Patricia Tellez', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (299,'nombreRegla299', 'FeUD Seguro Préstamo', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (129,'bonServ', 'Bonificación por servicios', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (230,'nombreRegla230', 'A.C. Quinquenio', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (244,'nombreRegla244', 'Asopro', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (253,'nombreRegla253', 'A.C. Sueldo Básico', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (149,'nombreRegla149', 'Ajuste Bonific.Libros', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2151,'nombreRegla2151', 'Coopacon Ahorro', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2125,'nombreRegla2125', 'Contraloria De Bogota', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2156,'nombreRegla2156', 'A.C.Incapacidad', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2160,'nombreRegla2160', 'Astrid Mendez Orduna', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2171,'nombreRegla2171', 'A.C.Upc Saludcoop', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2110,'nombreRegla2110', 'Nelly Cifuentes De Cardozo', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2140,'nombreRegla2140', 'Guido Humberto Valderrama', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2152,'nombreRegla2152', 'Edit. Y Lib. Herder Ltda.', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (278,'nombreRegla278', 'J&J Company Asociados Ltda', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (288,'nombreRegla288', 'Feud Ahorro Programado', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (142,'nombreRegla142', 'Devolución Upc Compensar', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2220,'nombreRegla2220', 'Martha Bonilla Estevez', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2227,'nombreRegla2227', 'Fondo Pensiones Skandia -Volun', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2229,'nombreRegla2229', 'Torres Guarin Y Cia Ltda -Segu', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1114,'nombreRegla1114', 'Mesada Adicional Diciembre', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1105,'subFamiliar', 'Subsidio Familiar Pensionados', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1213,'asigAdicDec', 'Asig.Adic.Dec./', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1220,'nombreRegla1220', 'Aju.Prim.Vac.X Exc. Acad.05.08', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2243,'nombreRegla2243', 'Greenmax Computadores-Suminist', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1234,'nombreRegla1234', 'Aju Mesada Por Retro 2.4% 2009', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2259,'nombreRegla2259', 'FeUD  Educacion Preescolar', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1245,'nombreRegla1245', 'Ajuste Suel.Bas.Vaca Retro', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2268,'nombreRegla2268', 'Cooefectiva Libranza', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (1257,'nombreRegla1257', 'Ajuste Asig.Decreto', 1, 1);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2280,'nombreRegla2280', 'Coop. Mult. Tecnocoop', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2290,'nombreRegla2290', 'Luz Marina Varela-Subsi. Famil', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2304,'nombreRegla2304', 'FeUD Impulso Cmpra De Vivienda', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2305,'nombreRegla2305', 'FeUD Compra Cartera', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2313,'nombreRegla2313', 'Laura Sofia Enciso- Sub.Fliar', 1, 2);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2322,'ibc_liquidado', 'Ingreso base de cotizacion', 3, 3);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2323,'licencia_rem', 'Licencia remunerada', 3, 3);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2324,'licencia_norem', 'Licencia no remunerada', 3, 3);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2325,'comision_estudio', 'Comisión de estudio', 3, 3);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2327,'ibc_novedad', 'Ingreso base de cotización para periodo que aplicó novedad', 3, 3);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2326,'comision_norem', 'Comisión no remunerada', 3, 3);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2328,'exterior_familia', 'Persona en el exterior con familia', 3, 3);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2330,'incapacidad_general', 'Incapacidad general', 3, 3);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2331,'exterior_sin_familia', 'Persona residente en exterior sin familia', 3, 3);
INSERT INTO administrativa.concepto_nomina(id, nombre_concepto, alias_concepto, tipo_concepto, naturaleza_concepto) VALUES (2329,'incapacidad_laboral', 'Incapacidad laboral', 3, 3);

INSERT INTO administrativa.tipo_preliquidacion(id, nombre, descripcion,activo) VALUES (0, 'Primera quincena','Pagada a principio de mes',TRUE);
INSERT INTO administrativa.tipo_preliquidacion(id, nombre, descripcion,activo) VALUES (1, 'Segunda quincena','Pagada a final del mes',TRUE);
INSERT INTO administrativa.tipo_preliquidacion(id, nombre, descripcion,activo) VALUES (2, 'Mes completo','Pagada a final del mes',TRUE);
INSERT INTO administrativa.tipo_preliquidacion(id, nombre, descripcion,activo) VALUES (3, 'Prima semestral','Pagada en junio',TRUE);
INSERT INTO administrativa.tipo_preliquidacion(id, nombre, descripcion,activo) VALUES (4, 'Prima de vacaciones','Pagada en diciembre',TRUE);
INSERT INTO administrativa.tipo_preliquidacion(id, nombre, descripcion,activo) VALUES (5, 'Sueldo de vacaciones','Pagada en diciembre',TRUE);
INSERT INTO administrativa.tipo_preliquidacion(id, nombre, descripcion,activo) VALUES (6, 'Prima de navidad','Pagada en diciembre',TRUE);
